#fullnameOverride: canary 

service:
  type: ClusterIP
  port: 80
  portName: # http
  targetPort:
  selectorLabels: # required
    # app: # chart-name-of-the-application

appMesh:
  enabled: false
  outsideTrafficAllowed: false # change to true if this Canary needs to be accessible from outside the mesh
  vRouterListenerProtocol: http

  targets:  # Uncomment snippet below to set route(s) to your existing back-end app Virtual Node
  #  - vNodeName: existing-vnode-for-service-v1
  #    weight: 9
  #  - vNodeName: existing-vnode-for-service-v2
  #    weight: 1
