{{- if (.Values.appMesh.enabled) and (.Values.appMesh.outsideTrafficAllowed) -}}
apiVersion: appmesh.k8s.aws/v1beta2
kind: GatewayRoute
metadata:
  name: {{ template "canary.fullname" . }}
  labels:
    app: {{ template "canary.name" . }}
    chart: {{ template "canary.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  httpRoute:
    match:
      prefix: /{{ template "canary.fullname" . }}
    action:
      target:
        virtualService:
          virtualServiceRef:
            name: {{ template "canary.fullname" . }}
{{- end -}}